### ISSUE TITLE
[Question] Duplicate the repository

### ISSUE THREAD

**Issue by Geod24** [dlang/dub-registry#114]
I'm looking to do some improvement to the REST interface (you wouldn't had guess, would you ? ;) ), so obviously I want to test my changes.
Is there any way I can dup the database ?

**Comment by s-ludwig** [comment]
This part still needs some work (automatic mirroring, admin users with access to all repors). For practical testing purposes I'd recommend to just register a user locally and add a few repositories from the public registry for testing.

**Comment by Geod24** [comment]
Looks like I should turn this into a proper issue then :)

Kinda unrelated to this issue, but related to my motivation:
- https://issues.dlang.org/show_bug.cgi?id=14636
- http://forum.dlang.org/thread/mkg3sm$1bk4$1@digitalmars.com

Any way I can email you (or you can email me, see my profile) ?

**Comment by s-ludwig** [comment]
Yeah, both would good to have (admin support would probably be the most helpful immediate improvement). For the mirroring support, we'd have to add a special mode of operation (read only and without authentication support) and then use the improved REST API ;) to query the latest changes.

I had a look at the NG thread now. You can reach me via sludwig at rejectedsoftware.com. If you have a Jabber account that would also be a possibility (I'm just often AFK currently).

**Comment by wilzbach** [comment]
@s-ludwig it would be great if you could do hourly dumps of the public info in the mongodb - they can overwrite the previous. I should be easy for me then to run a mirror of the registry and update it's database every hour.

Or do you have a better idea how we could do incremental imports?

**Comment by MartinNowak** [comment]
Now supported via `./dub-registry --mirror https://code.dlang.org`.
