### ISSUE TITLE
Markdown code blocks with empty lines rendered incorrectly

### ISSUE THREAD

**Issue by kyllingstad** [dlang/dub-registry#118]
Code/preformatted blocks which contain empty lines get split into several blocks. Besides looking ugly, it leads to incorrect indentation, among other things.

In other words, what should be rendered like this:

    void hello() {

        writeln("Hello World!");

    }

actually gets rendered like this:
```
void hello() {
```
```
writeln("Hello World!");
```
}

See the README section on the [zmqd page](http://code.dlang.org/packages/zmqd) for an example.

**Comment by kyllingstad** [comment]
Note that I'm talking about *indented* code blocks here. I haven't tried fenced code blocks.

**Comment by s-ludwig** [comment]
Fixed through https://github.com/rejectedsoftware/vibe.d/issues/1527.
