### ISSUE TITLE
copy+paste for dependency line

### ISSUE THREAD

**Issue by wilzbach** [dlang/dub-registry#140]
It would be quite nice to have a handy "copy to clipboard" button for the dependency line and hopefully soon to the `dub fetch` (#138).
Other packages manager like [rubygems](https://rubygems.org/gems/jekyll) or even github themselves provide this handy feature.

There is [clipboardjs](https://clipboardjs.com/), so adding this is easy and I would be happy to send a PR. The only question is how do you want me to integrate the bower dependency?
Are there some hooks in dub with which we could run `bower` (or `npm`)?

Related to #96 (copy+paste for shields).

**Comment by MartinNowak** [comment]
I wouldn't want a frontend dependency manager for such a simple addition, just copy the script.
We might choose to use bower for the site makeover.

**Comment by greenify** [comment]
> I wouldn't want a frontend dependency manager for such a simple addition, just copy the script.

Fair enough 

> We might choose to use bower for the site makeover.

Yep my question was in some sense more general - how does one integrate bower or npm with `dub`?
See #792
