### ISSUE TITLE
Support Markdown Table Syntax

### ISSUE THREAD

**Issue by JackStouffer** [dlang/dub-registry#143]
This

```
First Header | Second Header
------------ | -------------
Content from cell 1 | Content from cell 2
Content in the first column | Content in the second column
```

Makes this on Github

First Header | Second Header
------------ | -------------
Content from cell 1 | Content from cell 2
Content in the first column | Content in the second column

I use it in my `README.md` file and it's awkward for the plain text version to show on my dub page

**Comment by wilzbach** [comment]
Yep we use this too, so if someone needs a README file to test:

https://code.dlang.org/packages/mir
https://github.com/libmir/mir

**Comment by s-ludwig** [comment]
Fixed through https://github.com/rejectedsoftware/vibe.d/issues/1493.
