### ISSUE TITLE
No update triggered when the commit for the latest tag is amended

### ISSUE THREAD

**Issue by BBasile** [dlang/dub-registry#151]
...And the change in the amendment may be: update of the DUB description.

**Comment by s-ludwig** [comment]
The description should be linked to the tagged version of the package, so in the package list, it should always display the description at the time of the latest tagged version.

**Comment by BBasile** [comment]
Is an update triggered when the commit that matches to the latest tag is ammended / rebased ?

**Comment by s-ludwig** [comment]
If the tag is updated to point to the amended commit, then it pretty sure should, but I'll have to double-check.

**Comment by BBasile** [comment]
Ok, I've renamed the issue, this is the case I've encountered recently. If I commit some craps with a new tag the description is well updated.

**Comment by BBasile** [comment]
This problem will happen so often that's it's not worth implementing the check.
