### ISSUE TITLE
rank package (show and sort by downloads/stars/...)

### ISSUE THREAD

**Issue by Extrawurst** [dlang/dub-registry#159]
both bitbucket and github have systems like that and we could allow fetching them aswell and show them and allow users to sort the list using them, right ?

**Comment by wilzbach** [comment]
Yes there is already a github/bitbucket client - it could just fetch this information too. 
Implement it and it will appear on code.dlang.org ;-)

**Comment by zachthemystic** [comment]
+1, I think this is a good idea. For example, I'm just exploring the Atom editor, and their packages page can be sorted by stars, and it really helps to find popular and exciting packages:
https://atom.io/packages/list?direction=desc&sort=stars

**Comment by MartinNowak** [comment]
I'd want to try sth. along the lines of
```
0.1 * log10(#downloads) + log10(#stars) + 3 * proportion of green CI among last 10 results + 3 * log10(#dependants)
```
Rating should be cached/shown in a sortable column, showing breakdown on mouse hover.

**Comment by zachthemystic** [comment]
That would depend on stars existing in the first place, right? That'd be great.
