### ISSUE TITLE
Logo-link goes to 404

### ISSUE THREAD

**Issue by aka-demik** [dlang/dub-registry#165]
Logo link must be:
```html
<div class="logo">
	<a href="/">
		<img id="logo" alt="DUB Logo" src="/images/dub-header.png"/>
	</a>
</div>
```
Because, from `http://code.dlang.org/docs/commandline` or `http://code.dlang.org/packages/vibe-d`, logo-link goes to 404. Current state:
```html
<div class="logo">
	<a href=".">
		<img id="logo" alt="DUB Logo" src="/images/dub-header.png"/>
	</a>
</div>
```
I can PR with `a(href="/")` at this [line](https://github.com/dlang/dub-registry/blob/bf37554a4586a8a3128683c7edca8306d212fc0e/views/layout.dt#L19). But not sure it's right.

**Comment by bausshf** [comment]
See https://github.com/dlang/dub-registry/pull/154

**Comment by aka-demik** [comment]
Commit [d457beb](https://github.com/dlang/dub-registry/commit/d457bebaa84097c9cdd68f58d153be3edb25895d) has not yet deployed, or does not work?

**Comment by s-ludwig** [comment]
I indeed forgot to deploy it. Done now.
