### ISSUE TITLE
Usage statistics for libraries. (Stars + Downloads?)

### ISSUE THREAD

**Issue by schancel** [dlang/dub-registry#169]
Lots of package repositories (e.g. rubygems) show the number of downloads of a particular package, and there's some way to rate a library.   This would be extremely helpful for sorting through the libraries.  Also, the categories are a little weak.  It would be great to have some way to tag libraries/categorize libraries by their use.

If these things of statistics are amenable to the current project owners here, I'd be interested in working on them.

**Comment by MartinNowak** [comment]
I already have a few plans to restructure categories and searching.
We do have the download statistics in place (http://code.dlang.org/api/packages/vibe-d/stats), but they need to be integrated in the search results.
There is some WIP code for moving all the package sorting into the db, https://github.com/MartinNowak/dub-registry/commit/41a74a216be6b8aa9d26b0e644f2d8536015e718, number of downloads could just be another sortable column.
We thought about some more complex rankings, but I think download numbers are a really good proxy for any other metric.

**Comment by 9il** [comment]
Also the list of packages that is use for example Mir would be very helpful. So people would be able to see if their packages are used by another library. see #172

**Comment by MartinNowak** [comment]
Fixed by #224, https://code.dlang.org/?showrating
