### ISSUE TITLE
Api endpoint for list of all package+version

### ISSUE THREAD

**Issue by skoppe** [dlang/dub-registry#171]
It would certainly improve the html scraping I am doing now :)

**Comment by s-ludwig** [comment]
List of all package names: http://code.dlang.org/packages/index.json
List of all versions of a package (including package description for each version): http://code.dlang.org/packages/gsl.json

**Comment by BBasile** [comment]
I think he meant all the packages + their latest tag, eg
```
[
  {
    name: "libthis",
    latestVersion: "v1.0.2"
  },
  {
    name: "libthat",
    latestVersion: "v0.5.1"
  }
  /// etc, for each package...
]
```

It's currently very slow to get the list with the API ( (N package + 1) times get()) while the server could generate the JSON easily (see https://forum.dlang.org/post/ttxaazpxdhqpxidewffu@forum.dlang.org)

I'm also interested by this feature for Coedit.

**Comment by s-ludwig** [comment]
Okay, that sounds useful, too. I was hoping that the `/api/search?q=...` endpoint would help, but it returns no results for an empty search string.

**Comment by MartinNowak** [comment]
> Okay, that sounds useful, too. I was hoping that the /api/search?q=... endpoint would help, but it returns no results for an empty search string.

This might get fixed soon. I'm skeptical about an API that sends a whole db dump. We might at least need pagination.
If it's just the name and very few extra fields this might work though.

**Comment by skoppe** [comment]
Pagination FTW
code.dlang.org could also use it.

**Comment by MartinNowak** [comment]
> Pagination FTW
> code.dlang.org could also use it.

That one needs to become search centric.

**Comment by s-ludwig** [comment]
Now available: https://code.dlang.org/api/packages/search

**Comment by skoppe** [comment]
👍
