### ISSUE TITLE
documentation doesn't mention the "version" attribute.

### ISSUE THREAD

**Issue by KevinBrogan** [dlang/dub-registry#175]
### Details

When compiling the default "dub init" project with the verbose tag, a warning is emitted.

`dub -v`

> Note: Failed to determine version of package test at .. Assuming ~master.

Placing a "version":"~master" attribute in the root configuration will eliminate this error. Dub will generate the "version":"~master" attribute when using the "dub convert" command.
### Platform

Windows 10, x86_64, DUB version 1.0.0+28-geeff313, built on Aug 20 2016
### Reproduction

```
dub init
dub build -v
```

> Using dub registry url 'http://code.dlang.org/'
> Refreshing local packages (refresh existing: true)...
> Looking for local package map at C:\ProgramData\dub\packages\local-packages.json
> Looking for local package map at C:\Users\kevin\AppData\Roaming\dub\packages\local-packages.json
> Note: Failed to determine version of package test at .. Assuming ~master.
> ...

**Comment by andre2007** [comment]
Setting the version tag manually in dub.json is deprecated. The idea is that the version is determined by the git tag.
You can ignore the warning, it works as expected.
