### ISSUE TITLE
automatic documentation build

### ISSUE THREAD

**Issue by wilzbach** [dlang/dub-registry#185]
Like https://docs.rs/  (e.g. [here](https://docs.rs/fixedvec/0.2.3/fixedvec/struct.FixedVec.html)) the documentation could be automatically built by basically running running `dub build -b ddox` and storing the output somewhere.

While of course this doesn't have to be within the `dub-registry`, I though that this is the best place where people interested in improving code.dlang.org would look.

There is one project that goes into the direction: http://dpldocs.info, but only builds the docs for Phobos, druntime + arsd (it's based on [arsdox](https://github.com/adamdruppe/adrdox)).

**Comment by MartinNowak** [comment]
Done with the dpldocs link in #302
