### ISSUE TITLE
Unable to register or log-in

### ISSUE THREAD

**Issue by hatem-oraby-sociomantic** [dlang/dub-registry#198]
I've tried to create an dub account with an email but it failed on the first time with (what I think was) short-password error. When I tried to register again it tells me that the email is already registered. If I try to send reactivation email it tells me that the user is already activated, and if I try the forgot-password link it tells me that an email was sent but nothing ever is received.

Can you please check if something is broken in the chain or if I'm doing something wrong?.
The email I used is pretty much like this github's account user-name.

**Comment by s-ludwig** [comment]
Turned out I forgot to adjust the SMTP configuration after some recent infrastructure changes. The "forgot password" mail should arrive successfully now.

**Comment by hatem-oraby-sociomantic** [comment]
It all works good now :+1: , thanks.
