### ISSUE TITLE
Mirrormode doesn't sync READMEs

### ISSUE THREAD

**Issue by wilzbach** [dlang/dub-registry#212]
I currently don't have time to dig deeper into this, but for on the API dump endpoint (http://code.dlang.org/api/packages/dump) an empty readme is returned and the monitoring only queries the upstream mirror. So it doesn't try to fetch the README from GH on its own.

Hence, there are two options that we should think about:
- send the README on the package dump as well (might increase the size)
- do updates from the content provider on its own (would be interesting if the registry goes down, but I am not sure if it's worth the extra traffic and overhead to do needed AUTH credentials due to rate limits for unauthorized access).

edit: Of course there's also the point that it's just a fallback mirror for usage of the DUB executable in case the registry is temporarily down and not primarily intended for being browsable by users.

**Comment by MartinNowak** [comment]
README are fetched from raw github content so they shouldn't be rate limited.
https://github.com/dlang/dub-registry/blob/0e8e236007ce4d127f384c37ae325be18fe1e322/source/dubregistry/repositories/github.d#L90

**Comment by s-ludwig** [comment]
BTW, I didn't have the time to look into the issue more closely. But from a quick test, the readme fields have actually not been empty, but listed the file name as expected. So maybe in fact something else is the source of the issue.

**Comment by MartinNowak** [comment]
I've seen readmes for some packages missing, but now it seems to work.
Just dropped vpmreg and urlcache to confirm this. Maybe related to the vibe-d update or some stale cache.
