### ISSUE TITLE
GitLab support

### ISSUE THREAD

**Issue by Pulgovisk** [dlang/dub-registry#243]
Is GitLab support already completed?

**Comment by Pulgovisk** [comment]
The issue https://github.com/dlang/dub-registry/pull/207 is arleady closed, but the code.dlang.org not display the GitLab option
![captura de tela 14](https://user-images.githubusercontent.com/15163685/29214119-713ffe8a-7e7c-11e7-9c68-8ffe544dbc21.png)

**Comment by ohdatboi** [comment]
> Is GitLab support already completed?

Yes, it is. Looks like configuration file on the server should be updated. Ping @s-ludwig

**Comment by Pulgovisk** [comment]
@ohdatboi  Is Firefox 55 on Windows, but the problem also occurs on Linux, using Firefox 55
![issue](https://user-images.githubusercontent.com/15163685/29255428-af1651d0-8077-11e7-9dad-e2d3d062d367.png)

**Comment by ohdatboi** [comment]
@Pulgovisk I fixed styles in #244, but there is nothing I can do about GitLab support.

**Comment by s-ludwig** [comment]
There is some authentication token for gitlab in my config but it's commented out. I'll have to do dig a little deeper, because I can't remember right now whether I already created an account for this purpose or not.

**Comment by MartinNowak** [comment]
> There is some authentication token for gitlab in my config but it's commented out. I'll have to do dig a little deeper, because I can't remember right now whether I already created an account for this purpose or not.

Good point, just saved https://gitlab.com/dlang-bot in case we'll need it.
Apparently someone already registered https://gitlab.com/dlang.

**Comment by wilzbach** [comment]
> Apparently someone already registered https://gitlab.com/dlang.

Looks like it was @lindt (Stefan Rohe)

**Comment by lindt** [comment]
Seb, Martin, added you both just now as owners of https://gitlab.com/dlang

**Comment by Pulgovisk** [comment]
Is there any news for the GitLab support?

**Comment by s-ludwig** [comment]
I've registered a new "dub-registry" account and set up an API token now. You can register gitlab.com repositories, but the test package that I registered is still awaiting an update, so I'm not sure yet if there are any issues left.

**Comment by Pulgovisk** [comment]
The Gitlab support is now working.
