### ISSUE TITLE
Password reset doesn't work

### ISSUE THREAD

**Issue by testing-in-chrome** [dlang/dub-registry#266]
I tried several times across several days to reset my password, but all I got was the following message:

"An e-mail has been sent to you with your user name and a one-time link to reset your password."

However, I never get that email. I checked my Junk Email and Spam folders, nothing!

Please fix.

**Comment by testing-in-chrome** [comment]
Any updates on this issue?

**Comment by s-ludwig** [comment]
Found the cause. It was due to the transition from vibe.d's old Diet template module to diet-ng, which doesn't define the `:css` filter. I'll fix this and push an updated binary later today.

**Comment by s-ludwig** [comment]
New version has been deployed and it works for me again now.

**Comment by testing-in-chrome** [comment]
Thank you very much!
