### ISSUE TITLE
Package search should match partial matches

### ISSUE THREAD

**Issue by wilzbach** [dlang/dub-registry#268]
Example: search for `async`

https://code.dlang.org/search?q=async

Ideally it found find vibe-core too: https://code.dlang.org/packages/vibe-core

**Comment by MartinNowak** [comment]
Nope, not supported by MongoDB's FTS engine.
I think it will be addressed by indexing readmes and switching to tags.

**Comment by MartinNowak** [comment]
That's the new search result for async with indexed READMEs (#193).
![grafik](https://user-images.githubusercontent.com/288976/36022317-fdac0ea4-0d88-11e8-880b-3f7ba5b6cf7a.png)

**Comment by timotheecour** [comment]
https://github.com/dlang/dub/issues/1008

**Comment by timotheecour** [comment]
interestingly suffix search seems to work but not prefix search (see https://github.com/dlang/dub/issues/1008#issuecomment-365147845)

**Comment by timotheecour** [comment]
what I really don't understand is: why can't we just use regex search on package names?
https://docs.mongodb.com/manual/reference/operator/query/regex/
(could be via a different API, eg:
```
dub search query #uses existing API via mongodb FTS
// m_packages.find(["$text": ["$search": query]], ["score": bson(["$meta": "textScore"])]);
dub search_regex query #uses https://docs.mongodb.com/manual/reference/operator/query/regex/
// m_packages.find(["packages": ["$regex": query]]);
```

**Comment by MartinNowak** [comment]
Searching for asynchronous works, hardly any stemming library would fix this, only a synonym list would help for that. Less of a problem than most other #93 problems.
`msgpack-d` that's because the query is split at `-` and every package contains sth. about `d`.

**Comment by MartinNowak** [comment]
BTW, regex search can be done like this `dub search '' | grep query`.
