### ISSUE TITLE
Rating?

### ISSUE THREAD

**Issue by EmTee70** [dlang/dub-registry#284]
https://github.com/dlang/dub-registry/blob/master/views/search_results.dt
There is the part with the rating, when will it become visible?

Please consider to add the following from Adam, as a link:
https://forum.dlang.org/post/utsgnfsekdpntvfdrexg@forum.dlang.org

**Comment by andre2007** [comment]
In the meantime the score and the read me link provided by Adam is visible on code.dlang.org.
