### ISSUE TITLE
Add way to specify documentation link

### ISSUE THREAD

**Issue by jmdavis** [dlang/dub-registry#287]
Right now, you can specify where the source code lives, but there's no way to specify where the documentation lives. Of course, that can be listed in the README.md file as part of the text, but it would be nice if it could be listed at the top right along with the link to the repo. Then there could be a standard place to look on a package's page to see the link to its documentation.

**Comment by wilzbach** [comment]
This reminds me about donationUrl - https://github.com/dlang/dub/pull/1309

**Comment by WebFreak001** [comment]
fixed by #332 and #302
