### ISSUE TITLE
Packages are not updating

### ISSUE THREAD

**Issue by bausshf** [dlang/dub-registry#294]
For over a day packages aren't updating.

I've also noticed a lot of connection issues with the website, it has been down a lot.

Are there some troubles right now?

**Comment by s-ludwig** [comment]
After the latest deployment, for some reason SIGPIPE error start to occur after a while. I've partially reverted to an older vibe.d version to see if that was the issue.

**Comment by bausshf** [comment]
Thank you for the quick response.

I hope you get it resolved soon enough!
