### ISSUE TITLE
"Error 502 bad gateway" when trying to view a specific package

### ISSUE THREAD

**Issue by LaurentTreguier** [dlang/dub-registry#298]
I've recently registered a new package on code.dlang.org, named `dls` at version `0.1.0`. My `dub.json` file specified the package version manually, and going on the package page, I saw that this was considered obsolete. After a few changes to my package, removing the version from `dub.json` and tagging a new version (`0.1.1`), going to the package page gives me an almost blank page; and then code.dlang.org only gives "Error 502 bad gateway" when trying to see any other page for the next minute or so.
![image](https://user-images.githubusercontent.com/7602755/37817126-ee7bfbf2-2e75-11e8-9434-840429b79008.png)
Maybe this is somehow linked to #294 as the problem started occuring after an update to the package ?
I don't think I've done any wrong change from the `0.1.0` version, but if it is of any relevance, here are [the `dub.json` file](https://github.com/LaurentTreguier/dls/blob/master/dub.json) and [the changes from v0.1.0 to v0.1.1](https://github.com/LaurentTreguier/dls/compare/v0.1.0...v0.1.1).
Apart from the code, the only changes are adding a `REAME.md`, and removing the `version` section (as it's obsolete) and `configurations` section of `dub.json` (as dub detects the configurations automatically).

**Comment by wilzbach** [comment]
There's some discussion on #dub at Slack about this.
In short:
- it's due to https://github.com/vibe-d/vibe.d/issues/2132
- the Vibe.d PR is here: https://github.com/vibe-d/vibe.d/pull/2133

**Comment by WebFreak001** [comment]
you can wait until this patch is applied to dub (who knows when), or you can remove the subcolumns in the table in your readme which breaks it. (You have more columns than header columns somewhere)

**Comment by LaurentTreguier** [comment]
I'm using `|` in the contents of my table, inside backquotes... I guess that's what's breaking everything. I'll update my README and push an updated version in the next few days (it's not urgent anyway)

**Comment by LaurentTreguier** [comment]
Removing the pipes in my table indeed fixes it. I'm closing this since there is already an issue and a PR

**Comment by s-ludwig** [comment]
The quickfix for the crash has been deployed, but I'll open separate issue against vibe.d for the correct output.

**Comment by wilzbach** [comment]
I can still crash the registry when I open http://code.dlang.org/packages/dls

**Comment by LaurentTreguier** [comment]
Weird... It doesn't seem to happen to me anymore, I can see the page just fine now

**Comment by wilzbach** [comment]
A sorry. Probably was a super-aggressive browser cache.
