### ISSUE TITLE
Make it possible to either turn off the documentation tab or point it elsewhere

### ISSUE THREAD

**Issue by jmdavis** [dlang/dub-registry#312]
It looks like a "Documentation" tab was recently added to the projects on code.dlang.org, and code.dlang.org gives no control whatsoever over where it points to. It looks like it currently points to dpldocs.info, which in the case of dxml looks terrible because I actually went to the effort of properly defining link macros and the like in the documentation, which then of course aren't recognized by the tool being used. As such, I don't want there to be a link to http://dxml.dpldocs.info/dxml.html on the [code.dlang.org page for dxml](https://code.dlang.org/packages/dxml). I already have a link to the properly generated documentation in the readme that gets displayed. As such, I would like to either be able to get rid of the Documentation tab or point it to the proper documentation. The dpldocs bit may be great for a project that didn't bother to go to the effort of putting together nice documentation, but any project that actually really uses ddoc is going to look terrible with it. And now, because that Documentation tab is on the top in big letters, folks are more likely to click on it and see the badly generated documentation instead of the official documentation.

So, _please_ make it possible to at least configure what that Documentation tab points to.

**Comment by bausshf** [comment]
I second this, also some libraries etc. may prefer other documentation, than just their api.

For: http://code.dlang.org/packages/diamond I'd actually prefer if it was linked to: http://diamondmvc.org/docs since it has a more in-depth documentation on how to use it.

**Comment by WebFreak001** [comment]
I'm going to make it automatically determine the documentation from the readme if it contains a link labeled `documentation` or `reference`

**Comment by WebFreak001** [comment]
of course I would still recommend using dpldocs instead as it automatically updates and deploys the docs. Though I forgot to add the version to the link in my PR

**Comment by bausshf** [comment]
@WebFreak001 well my documentation page for Diamond links to dpl docs too as the api docs, so in my case it would work best with what I provided, but thanks for the heads up will update the read me to reflect that

**Comment by WebFreak001** [comment]
the following are planned:
```
[...Documentation...](link)
[...Reference...](link)
...Documentation|Docs: link
...Reference(s): link
```
case insensitive of course

**Comment by jmdavis** [comment]
Please add a way to actually configure the link. I don't know why it shouldn't be configurable just like the repo location is configurable. And looking over the readme for dxml, looking for links like you describe would not find its documentation link. I can adjust it if I have to, but the way it is right now makes good sense, and it makes a lot more sense to me that the documentation link would be configurable rather than having to make the readme look a certain way for code.dlang.org to figure it out for you.

**Comment by wilzbach** [comment]
Yes, please let's simply make it a field.
I'm aware that adding this to the `dub.json|sdl` [didn't work out yet](https://github.com/dlang/dub/pull/1309), but with "auto-detecting" there are so many things that go wrong and it's hard to test and will require extra documentation.

**Comment by MartinNowak** [comment]
Maybe documentation should only be linked in the readme, leaving it to package maintainers to choose the right hosting. That also meant consistency between GH and code.dlang.org.

**Comment by bausshf** [comment]
@MartinNowak But in some cases it makes no sense to link to documentation from GH, because you already link to ex. a website where the docs are available and thus you'll basically have an extra link to both the site and the documentation (which exist on the same site.)

Honestly it should be a configuration in the package manager since that's the one that needs it.

It would be an unnecessary dependency from GH that can be completely avoided.

**Comment by bausshf** [comment]
At least have an option to override it from a form field, which would generally be a more user-friendly way, rather than some "hack".

**Comment by wilzbach** [comment]
Simple PR to allow overwriting the documentation_url -> https://github.com/dlang/dub-registry/pull/332
