### ISSUE TITLE
Can't update packages

### ISSUE THREAD

**Issue by bausshf** [dlang/dub-registry#321]
I can't seem to update my packages

It says the following when I trigger manual updates:

```
Packages are automatically updated, so there is no need to trigger an update manually. Please, be patient.

Package is currently being updated.
``` 

But nothing happens.

It has been about a day since my package should have been updated.

I don't know if it's possible for you to manually do something?

The package I'm trying to update is this: https://code.dlang.org/packages/diamond

**Comment by bausshf** [comment]
Okay closing this. I can see my mistake. I put wrong tag on it.

My bad.

**Comment by wilzbach** [comment]
FYI: We recently merged https://github.com/dlang/dub-registry/pull/291, so manually triggering an update should be really fast nowadays
