### ISSUE TITLE
Support for private bitbucket repositories

### ISSUE THREAD

**Issue by the-Mitu** [dlang/dub-registry#328]
Hello,

I'd like to request a feature to support the login credentials and operating on private repositories for BitBucket as well. By looking at the code I see that it is possible to provide credentials for GitHub and GitLab, but not for BitBucket ATM.

**Comment by rracariu** [comment]
Worked  on at https://github.com/dlang/dub-registry/pull/353

**Comment by rracariu** [comment]
This should be closed.  The registry now supports private bitbucket repos.
