### ISSUE TITLE
GitLab API v3 is no longer supported, use v4 instead

### ISSUE THREAD

**Issue by WebFreak001** [dlang/dub-registry#342]
Tried to import a repository gave this error on the dub registry:

Failed to read JSON from https://gitlab.com/api/v3/projects/WebFreak001%2Fbancho-irc/repository/branches?private_token=sjpcNjkSC-a4dFBNnzzD: Unexpected reply for 'https://gitlab.com/api/v3/projects/WebFreak001%2Fbancho-irc/repository/branches?private_token=sjpcNjkSC-a4dFBNnzzD': Gone

**Comment by Member1221** [comment]
Having this issue trying to update my package to a gitlab mirror, myself.

**Comment by WebFreak001** [comment]
fixed by #345
