### ISSUE TITLE
You must accept new ToS

### ISSUE THREAD

**Issue by WebFreak001** [dlang/dub-registry#343]
@s-ludwig 
403 Forbidden  - You (@dub-registry) must accept the Terms of Service in order to perform this action. Please access GitLab from a web browser to accept these terms.

Got that by clicking an errored link shown in the web interface. It exposes the private token of the API and is broken anyway.

Please make sure you generate a new access token and remove that one if you do.

**Comment by wilzbach** [comment]
I think this has been resolved.
