### ISSUE TITLE
Gitea support?

### ISSUE THREAD

**Issue by LunaTheFoxgirl** [dlang/dub-registry#344]
I see there's a PR for Gogs support, have you considered Gitea support? Gogs is very slow at updating and some people has forked gogs and made gitea, which is a community effort. @s-ludwig.
Its API is way more fully fletched and should be easier to integrate.

**Comment by bausshf** [comment]
I would like to see this too!

**Comment by dhasenan** [comment]
I took a look at it.

[Here's Gitea's API.](https://try.gitea.io/api/swagger) Every endpoint requires authentication, which requires a user. But the API doesn't let you register a user.

The process of registering your project hosted on gitea would be:

1. Set DISABLE_REGISTRATION in your gitea config to false. Double-check that API access is turned on. Restart gitea.
2. Create a new user.
3. Enable API access for that user and disable everything else.
4. Create an API token for them.
1. Input your project URL in the dub registry.
3. Tell dub that it's hosted on gitea.
6. Give it the auth token you just made.
7. Tell it where your README is located.

There are two alternatives:

1. Dub parses gitea's HTML frontend. This will be a bit slow, and more importantly it will break without notice. Worse, this is a self-hosted system, so dub would have to support many versions of gitea HTML.
2. Dub uses git instead, costing the registry a lot more disk space, bandwidth, and time, but supporting every git repository (such as git.gnome.org).

**Comment by Member1221** [comment]
You dont need DISABLE_REGISTRATION if you have admin access on the server, then you can just create a new user via the admin UI.

**Comment by Member1221** [comment]
Aswell my testing shows that I don't need authentication for the GET requests. Maybe the repos you are trying to read are private?

Public repositories work fine without authentication.

**Comment by dhasenan** [comment]
Apparently older versions of gitea required authentication for everything. (I'm on 1.1.3, and it's not trivial to upgrade.) https://git.ikeran.org/api/v1/repos/dhasenan/webkit-d for instance says 401 Unauthorized.

**Comment by Member1221** [comment]
Well you don't need to list files afaik, just download a recent archive.

**Comment by dhasenan** [comment]
Right. It's a *bit* of a problem, not a show-stopper. It means that dub needs to use more bandwidth (for itself and for the remote gitea server), time, and disk space to get the data it needs.

**Comment by ljmf00** [comment]
If there is no effort to support this, I would like to try it, in a near future :smiley:

**Comment by s-ludwig** [comment]
Opened a PR: #553
