### ISSUE TITLE
Invalid permissions for the gitlab token

### ISSUE THREAD

**Issue by Member1221** [dlang/dub-registry#348]
![billede](https://user-images.githubusercontent.com/7032834/41464946-5c1985d6-709c-11e8-9493-baa11f858e88.png)

The gitlab token specified on the production server does not have all of the permissions (which is required in API v4 for dub-registry's usecase will work)

**Comment by s-ludwig** [comment]
A new token has been set now and appears to work (tested using `gitlab-test-package`)
