### ISSUE TITLE
Internal server error for projects hosted via gitlab

### ISSUE THREAD

**Issue by Member1221** [dlang/dub-registry#349]
I am not sure what causes this issue.

Log from command: `dub fetch -v ppc`
```
Using dub registry url 'https://code.dlang.org/'
Refreshing local packages (refresh existing: true)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /home/clipsey/.dub/packages/local-packages.json
Determined package version using GIT: serve-d 0.1.3+commit.7.ga6a358e
Determined package version using GIT: trans-game ~master
Fetching ppc 0.0.2-alpha.2...
Downloading from 'https://code.dlang.org/packages/ppc/0.0.2-alpha.2.zip'
Getting a release version failed: HTTP request returned status code 500 (Internal Server Error)
Retry with ~master...
Fetching ppc ~master...
Downloading from 'https://code.dlang.org/packages/ppc/~master.zip'
HTTP request returned status code 500 (Internal Server Error)
```

**Comment by ohdatboi** [comment]
I couldn't reproduce this issue on my local machine, but internal server error indeed happens when using registry at code.dlang.org.

One more affected package: trial. Downloading https://code.dlang.org/packages/trial/0.7.0-rc.1.zip fails with:
```
$ curl https://code.dlang.org/packages/trial/0.7.0-rc.1.zip   
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>
```

**Comment by gedaiu** [comment]
I can confirm that my package crashes the registry... I wonder why... maybe because I recently moved it to gitlab?

**Comment by gedaiu** [comment]
I moved my repo back to github... It looks like the gitlab integration is broken..

**Comment by wilzbach** [comment]
FWIW I tried this locally with the d package and from my Arch and the docker container we should I get no errros and the zip is correctly returned.
Maybe someone who can reproduce this locally can provide a stack trace (e.g. with `gdb` or `registerMemoryError` in `source/app.d`).

**Comment by the-Mitu** [comment]
I noticed that for me dub-registry crashes only when I build with release (or release-debug) mode.

**Comment by jmdavis** [comment]
I get a 500 every time I try to use https://code.dlang.org/packages/libdiscid, and that's with just `dub build` or `dub upgrade` (no release or release-debug), and that project is hosted on gitlab. If I run either command with `-v`, it clearly shows that `Downloading from 'https://code.dlang.org/packages/libdiscid/0.6.0.zip'` is the last command before the 500. And if I try to wget that URL, it gives a 502 (bad gateway).

**Comment by ZombineDev** [comment]
@jmdavis the registry stores archived copies of registered packages. Most likely something prevented the registry from making a copy of the repo hosted on GitLab, but for some reason it doesn't gracefully handle this case.

**Comment by ohdatboi** [comment]
We discussed this issue on Slack and what happens is that registry built in release mode crashes when it tries to get release archive from the GitLab (even though username and password are defined in settings.json).

Building registry in debug mode fixes the problem.

**Comment by Member1221** [comment]
I think it has to do with the access tokens; I was the one that patched the new API in; but the API change on gitlab requires different permissions to be set. The best is to just enable all permissions.

**Comment by jmdavis** [comment]
The repo is public. What possible permissions could there need to be set beyond that? Anyone can clone the repo or download the code.

**Comment by Member1221** [comment]
The API/Bot/Client needs permissions API side to read/modify repositories. Note this is done for the bot itself; not on repositories.

**Comment by ljmf00** [comment]
Same here with project.
![image](https://user-images.githubusercontent.com/5050669/49706430-ca1dc580-fc1d-11e8-9ab7-719650f4d797.png)

---
- [1] https://gitlab.com/aurorafossorg/p/framework/core
- [2] https://code.dlang.org/packages/aurorafw
