### ISSUE TITLE
[dub.pm] Link to SDL doc page from JSON doc page broken (and vice versa)

### ISSUE THREAD

**Issue by zorael** [dlang/dub-registry#402]
The [JSON package format documentation page](https://dub.pm/package-format-json.html) has a link to the equivalent SDL package format documentation page ("See also the specification based on SDLang"), but it is broken, leading only to `http://127.0.0.1:8005/package-format?lang=sdl`.

Likewise the JSON page link on the SDL page.

**Comment by wilzbach** [comment]
Fix: https://github.com/dlang/dub-docs/pull/14
