### ISSUE TITLE
.travis-ci.yml is failing due to botan deprecation errors

### ISSUE THREAD

**Issue by ljmf00** [dlang/dub-registry#406]
The current config of travis-ci is failling because https://github.com/etcimon/botan package is basically dead and outdated.

Is `botan` really worth it? `dub-registry` seems using `openssl` on production, so at least it works.

**Comment by wilzbach** [comment]
Yeah, botan looks to be unmaintained (see also: https://github.com/etcimon/botan/issues/49).

Thus, probably the best action is to remove those two jobs (or at least allow them to fail).

**Comment by ljmf00** [comment]
Fixes with #407 .
