### ISSUE TITLE
Broken link on package page

### ISSUE THREAD

**Issue by Flying-Toast** [dlang/dub-registry#420]
Clicking on the "Score" link on a package's page:
![score](https://user-images.githubusercontent.com/38232168/55689392-d27ad880-5951-11e9-9263-8e380e1d8b64.png)

Leads to this broken link: https://dub.pm/commandline#package-scoring

Caused by: https://github.com/dlang/dub-registry/blob/master/source/dubregistry/viewutils.d#L82

**Comment by Flying-Toast** [comment]
Does anyone know where the new location of https://dub.pm/commandline#package-scoring is, or if it even exists anymore at all?

**Comment by ZombineDev** [comment]
The link should most likely point to https://dub.pm/develop#package-scoring.
