### ISSUE TITLE
Not reading BitBucket username/password correctly

### ISSUE THREAD

**Issue by TransientResponse** [dlang/dub-registry#429]
I'm unable to add private BitBucket repos to Dub. I've created a `settings.json` in the root of the Docker image with this Dockerfile:
```
FROM dlangcommunity/dub-registry
COPY settings.json /
```

And settings.json has the form:
~~~json
{
    "bitbucket-user": "<username>",
    "bitbucket-password": "<app_password>"
}
~~~
(redacted values of course)

If I copy-paste those values into a browser for the BitBucket 1.0 API, I get the correct response for my repo. But within Dub I get this error:
```
Failed to read JSON from https://api.bitbucket.org/1.0/repositories/<team>/<repo>: Unexpected reply for 'https://api.bitbucket.org/1.0/repositories/<team>/<repo>': Forbidden 
```

Am I just stupid and put my settings.json in the wrong place? If so, I will happily close this issue in shame :)

**Comment by WebFreak001** [comment]
the exception there would show `***:***@api.bitbucket.org` as host if it was picking up your username and password, so there is some configuration issue probably.

Try moving your settings.json into `/dub/settings.json` instead: https://github.com/dlang/dub-registry/blob/master/docker-entrypoint.sh#L18

**Comment by TransientResponse** [comment]
Thanks for the information. What I had to do was add a `COPY settings.json /opt/dub-registry/settings.json` into my Dockerfile. For future info, for anyone else reading this, a simple copy into `/dub` will get wiped out if you're mounting a volume to that directory (which you should to keep your data persistent).
