### ISSUE TITLE
Settings page not listed on code.dlang.org

### ISSUE THREAD

**Issue by andre2007** [dlang/dub-registry#433]
On [http://code.dlang.org](http://code.dlang.org/) the ```Settings``` page is not listed in menu ```Documentation```. Only when you click one entry, you are forwarded to [https://dub.pm/](https://dub.pm/) and now ```Settings``` page is listed.

**Comment by wilzbach** [comment]
That's because those are two different sites. code.dlang.org == dub-registry, dub.pm ==dub-docs.
So we need to add the menu item change here as well: https://github.com/dlang/dub-registry/pull/437

Might take some time until Sönke deploys this though.
