### ISSUE TITLE
Dub add not as ergnomic as old copy-paste way

### ISSUE THREAD

**Issue by dkorpel** [dlang/dub-registry#439]
So apparently #391 has been merged a while ago, but I recently noticed I miss the simple dub.json / dub.sdl copy-paste boxes. 
I simply wanted to quickly add a `d-graphviz` dependency for `buildType "unittest"`.
I thought I could easily use `dub add` and move the dependency manually inside my buildType, but it completely rewrote my dub.sdl removing comments and re-ordering buildOptions etc.

I'm not sure whether I want the old copy-paste boxes back, but at least the new `dub add` method should be as ergonomic as the old way. Doing `dub add` + find and copy the line + undo + paste in right place is a lot more clumsy than copy the line + paste in the right place.

**Comment by dkorpel** [comment]
I just realized that the `dub add` thing is really a [dub issue](https://github.com/dlang/dub/issues) and not an issue in the registry, but I encountered this as a regression in the registry so I'm interested in hearing what other people think about this before moving the issue there.

**Comment by andre2007** [comment]
@dkorpel please see also the pr discussion:
https://github.com/dlang/dub/pull/1587

**Comment by 0xEAB** [comment]
I’d say, this has been resolved as of 36a3cb5edd854c0ddd2f718ccbb0381f40c1d4fd.
Is there anything left that falls into the responsibility of the registry?
