### ISSUE TITLE
Certificate for dub.pm is expired

### ISSUE THREAD

**Issue by pbackus** [dlang/dub-registry#440]
Attempting to visit any package's short URL using HTTPS (for example, https://vibe-d.dub.pm) currently fails, because the certificate for `*.dub.pm` expired on April 24, 2019 and has not been renewed.

**Comment by Imperatorn** [comment]
Is this still the case?

What is required to fix it and who can do it?

**Comment by pbackus** [comment]
Yep, still broken.

I don't know who has access to the infrastructure for this. Your best bet is probably to ask on Slack.

**Comment by Geod24** [comment]
Fixed.
