### ISSUE TITLE
dub relies on removed Bitbucket API to get tags

### ISSUE THREAD

**Issue by gmueckl** [dlang/dub-registry#444]
I have dub projects hosted on bitbucket and the dub server complains that it cannot get an updated list of tags from the repository:

```
Failed to get GIT tags/branches: Failed to get tags: Failed to read JSON from https://api.bitbucket.org/1.0/repositories/gmueckl/sml-d/tags: Unexpected reply for 'https://api.bitbucket.org/1.0/repositories/gmueckl/sml-d/tags': Gone 
```

When accessing that URL, the result is:

```
{"type": "error", "error": {"message": "Resource removed", "detail": "This API is no longer supported.\n\nFor information about its removal, please refer to the deprecation notice at: https://developer.atlassian.com/cloud/bitbucket/deprecation-notice-v1-apis/"}}
```

From this, I take it that dub needs to be updated to use use the new API.

**Comment by gmueckl** [comment]
Can we please get this issue fixed? There are some dub packages for which new versions don't get picked up because of this and using workarounds for this is annoying.

**Comment by s-ludwig** [comment]
Should be fixed by #445. Can you verify (the fix has been deployed by now) and close this if this was successful?

**Comment by gmueckl** [comment]
Seems like I left a bug in PR #445. The date and time parser fails on the tag timestamp: 

`Failed to get GIT tags/branches: Failed to process ref v0.1.1: Invalid ISO String: 2019-10-31T11:02:46+00:00 `

I'll try to correct that.

**Comment by gmueckl** [comment]
PR #448 is the suggested fix for the timestamp parsing issue. Can we please get it merged? Thank you!

**Comment by WebFreak001** [comment]
PR looked good and was merged, needs deploy now @s-ludwig

**Comment by Geod24** [comment]
I believe it was deployed.
