### ISSUE TITLE
Transfer ownership of symmetry packages

### ISSUE THREAD

**Issue by John-Colvin** [dlang/dub-registry#450]
Please could the following packages be transferred to the new symmetry_investments account.

* [x] http://code.dlang.org/packages/autowrap
* [x] http://code.dlang.org/packages/sspi-d
* [x] http://code.dlang.org/packages/influx-d
* [x] http://code.dlang.org/packages/excel-d
* [x] http://code.dlang.org/packages/symmetry-linux
* [x] http://code.dlang.org/packages/jupyter_wire
* [x] http://code.dlang.org/packages/nanomsg-wrapper

the list is incomplete, @kaleidic, @atilaneves & @burner please add more from the list you can see in your code.dlang.org account.

**Comment by s-ludwig** [comment]
Transferred the 5 ones above, keeping the ticket open for anything that's left.

**Comment by atilaneves** [comment]
I just added two more.

**Comment by s-ludwig** [comment]
@atilaneves: I think we might have had an editing-clash there when I checked the boxes and an addition might have been lost.

**Comment by s-ludwig** [comment]
Oh okay, now it's there.

**Comment by Geod24** [comment]
Looks like it's all done.
