### ISSUE TITLE
Registry is down

### ISSUE THREAD

**Issue by voodooattack** [dlang/dub-registry#454]
I'm getting "502 bad gateway" for https://code.dlang.org/ and a timeout for https://code-mirror.dlang.io/

**Comment by szpak** [comment]
I observe the same:
```
Error querying versions for optional, registry at https://code.dlang.org/ (fallback ["registry at http://code.dlang.org/", "registry at https://code-mirror.dlang.io/", "registry at https://code-mirror2.dlang.io/", "registry at https://dub-registry.herokuapp.com/"]): HTTP request returned status code 503 (Service Unavailable)
Selected package optional 0.6.3 doesn't exist. Using latest matching version instead.
```

**Comment by schveiguy** [comment]
Should this be closed?

**Comment by wilzbach** [comment]
While availability has improved, we still have much work to do to improve to an expected uptime > 99.9%, so I would leave this issue open as a tracker and reminder.

**Comment by s-ludwig** [comment]
Do you still get outages? codemirror.dlang.org still has issues, but code.dlang.org should run pretty solid.

**Comment by WebFreak001** [comment]
with the dub command line I haven't had any problems in the past few months (not on my PC and not in CI) so that already runs pretty well. (and I guess using mirrors works better now too?)

For the website I thought I was seeing one or two crashes in that time but that could just be me misremembering too.

**Comment by wilzbach** [comment]
I have seen a few failures on the Buildkite project tester over the last three months, but I don't remember them enough to say whether it was GitHub's or the dub registry's fault. I will keep a closer eye 👀 in the future.
