### ISSUE TITLE
> 100 version tags are ignored

### ISSUE THREAD

**Issue by adamdruppe** [dlang/dub-registry#456]
see the code:

https://github.com/dlang/dub-registry/blob/master/source/dubregistry/repositories/github.d#L45

this broke our day job project because an update refuses to appear on a dependency.

**Comment by atilaneves** [comment]
In particular, right now this fails: `dub fetch mir-algorithm --version=3.3.11`. The tag [exists on the repository at github](https://github.com/libmir/mir-algorithm/releases/tag/v3.3.11), but code.dlang.org doesn't see it.

**Comment by WebFreak001** [comment]
my current plan:
- use Link header (follow until there is no "next" page anymore, then concat result) - 0%
- Link header may contain Hypermedia links (URL templates), so I need to implement an URL template parser first - 90%

potential issue: a tag could be added while scanning through the pages, making one tag appear twice or a tag could be removed, making one tag be missing

**Comment by adamdruppe** [comment]
On Tue, Apr 07, 2020 at 03:53:04AM -0700, Jan Jurzitza wrote:
> - Link header may contain Hypermedia links (URL templates), so I need to implement an URL template parser first - 90%

oh I've never seen that, got a link i can read?

> potential issue: a tag could be added while scanning through the pages, making one tag appear twice or a tag could be removed, making one tag be missing

Yeah, the server is supposed to handle that for you by using a cursor in
the page... of course Rails is a dumpster fire of useless trash so it
probably doesn't, still though I wouldn't worry too much about it at
this time.

**Comment by WebFreak001** [comment]
> oh I've never seen that, got a link i can read?
see https://developer.github.com/v3/#pagination

`This Link response header contains one or more Hypermedia link relations, some of which may require expansion as URI templates.`

I finished the URL template parser now too and extensively tested it, should probably become a separate dub package at some point. (It's fully documented and 100% tested already) The code for it is on my fix-456 branch of dub-registry in uritemplate.d

So I'm working on the pagination now
