### ISSUE TITLE
Transfer ownership for package 'mail'

### ISSUE THREAD

**Issue by anton-dutov** [dlang/dub-registry#459]
Hello i'm owner of **mail** package, i no longer maintain this package and want transfer ownership to **opticron** (repository already scheduled for transfer) , what procedure for?

**Comment by opticron** [comment]
I verify that I am willing to accept ownership of the mail package on code.dlang.org under the username opticron there as well.

**Comment by opticron** [comment]
Any progress on this?

**Comment by Geod24** [comment]
I think only @s-ludwig can do that.

**Comment by opticron** [comment]
HAH, thanks for finding this! I'll get back on it probably over the holidays.
