### ISSUE TITLE
Registry is currently frozen

### ISSUE THREAD

**Issue by Geod24** [dlang/dub-registry#462]
@s-ludwig : https://forum.dlang.org/thread/ucaagbhkioiwuzecegmw@forum.dlang.org
Tags don't seem to have propagated for at least 6 days, and someone mentioned the download counters being frozen.

**Comment by muv1** [comment]
https://github.com/dlang/dub/issues/1957

**Comment by muv1** [comment]
https://github.com/huntlabs/hunt-http/issues/15

**Comment by Geod24** [comment]
Ping @s-ludwig the registry has been frozen for at least two weeks.

**Comment by qznc** [comment]
Noticed this as well. I assume it was because my repo moved to the dlang-community organization. 

The "manage package" page shows this error:

    Failed to get GIT tags/branches: Failed to get tags: Failed to read JSON from https://***:***@api.github.com/repos/dlang-community/d-money/tags?per_page=100: Second attempt to send HTTP request failed.

**Comment by wilzbach** [comment]
Maybe the GitHub credentials used by the registry got invalidated?

**Comment by Geod24** [comment]
Well it seems to have came back, packages have been updated recently, e.g.  `unit-threaded` was released after libdparse.
However it's still failing for at least libdparse...

**Comment by mingwugmail** [comment]
Some package works: right now on https://code.dlang.org/

symmetry-imap 0.1.2
IMAP client library
updated 5 hours ago

while others don't: https://code.dlang.org/packages/money

which is also updated 5 hours ago

https://github.com/dlang-community/d-money/releases

**Comment by mingwugmail** [comment]
Maybe it's because of this d-money https://code.dlang.org/packages/money repo's setup issue?

I just saw on https://code.dlang.org/

The other package I reviewed showed up:

fixedpoint 0.1.1
Decimal fixed point type
updated 17 minutes ago

But this https://code.dlang.org/packages/money package's update is not picked up.

**Comment by MoonlightSentinel** [comment]
Any updates? The registry still hasn't updated libdparse ....

**Comment by Geod24** [comment]
This works now, thanks to Sonke's fixes.
