### ISSUE TITLE
Failed to get GIT tags/branches

### ISSUE THREAD

**Issue by tirithen** [dlang/dub-registry#463]
Hi, I started publishing my first set of dub packages a few weeks ago, to experiment and learn, on and off the last weeks I have seen an exclamation mark next to the package name and if I go to manage the package I get errors about the web page failed to fetch the git tags from the github api. I have sometimes clicked to manually update, then the message often goes away, but the next day they are back again.

Thanks for an otherwise nice package service. :)

```
Failed to get GIT tags/branches: Failed to get tags: Failed to read JSON from https://***:***@api.github.com/repos/d-utils/message/tags?per_page=100: Second attempt to send HTTP request failed. 
```

![Skärmbild från 2020-06-07 19-22-26](https://user-images.githubusercontent.com/245811/83975448-55037d00-a8f4-11ea-9697-997f5febd48a.png)

**Comment by wilzbach** [comment]
Please see https://github.com/dlang/dub-registry/issues/462 for some insights. Unfortunately there's currently only one person with access to the registry, so there's not much we can do immediately to help you.

**Comment by tirithen** [comment]
Thank you for the answer and the link, it works well enough for me as is, I guess I just wondered if I did something wrong as I'm new to the D ecosystem. I'm closing this issue and I'll follow #462. :)
