### ISSUE TITLE
Unable to upload package logo

### ISSUE THREAD

**Issue by tirithen** [dlang/dub-registry#464]
I'm not able to upload logo for my packages on https://code.dlang.org/ . I tried with png images with the two sizes 1024x1024 (61kb) and 512x512 pixels (34.3kb). It's not the most critical thing to fix but wanted to give a heads up.

```
Failed to generate logo: Failed to invoke the logo conversion process.
```

![Skärmbild från 2020-06-07 21-30-48](https://user-images.githubusercontent.com/245811/83978200-2d1d1500-a906-11ea-9350-7922a17d4f0b.png)

**Comment by s-ludwig** [comment]
Works again now. ImageMagick was not installed on the new server.

**Comment by tirithen** [comment]
Thanks! Works fine now.
