### ISSUE TITLE
GitLab readFile() regression

### ISSUE THREAD

**Issue by sarneaud** [dlang/dub-registry#471]
This regression in GitLab is breaking GitLab package management on the DUB registry:
https://gitlab.com/gitlab-org/gitlab/-/issues/212216

This is what I see in the registry:
```
Branch ~master: Unexpected reply for 'https://gitlab.com/api/v4/projects/sarneaud%2Furllibparse/repository/files/%2Fdub.json/raw?ref=2d5e3b631d6fcf4e21a59fde58cd57bade5e442c&private_token=***': Bad Request
```

Here's what's happening:
```
$ http get https://gitlab.com/api/v4/projects/sarneaud%2Furllibparse/repository/files/%2Fdub.json/raw?ref=2d5e3b631d6fcf4e21a59fde58cd57bade5e442c
HTTP/1.1 400 Bad Request
[Snip some headers]

{
    "error": "file_path should be a valid file path"
}

```

It works without the `%2F` before `dub.json` in the URL, just like in the GitLab bug report I linked above.

Maybe the fix is to just remove leading slashes from `path` here: https://github.com/dlang/dub-registry/blob/a7dfcd9eead171377eee098c07f134d595a5a8df/source/dubregistry/repositories/gitlab.d#L126

**Comment by Geod24** [comment]
CC @vitalka200

**Comment by AntonMeep** [comment]
I ran into the same issue, none of my packages were getting updates for the past half a year 🤦 

Also interesting how `urlEncode` changes / to %2F between repository's owner and project name in `getAPIURLPrefix()` function, seems like GitLab doesn't care but from what I read online some web services trip over url-encoded slashes.

**Comment by WebFreak001** [comment]
the GitLab API forces you to use %2F

**Comment by sarneaud** [comment]
It's the leading slash in the path that's the problem.  Gitlab consolidated its input validation code, and the result is that absolute paths are forbidden across (all?) API calls.  The files API previously allowed absolute paths but treated them like relative ones.
