### ISSUE TITLE
No release for over 2 years

### ISSUE THREAD

**Issue by schveiguy** [dlang/dub-registry#472]
I just tried dub run dub-registry, and v2.3.0 doesn't compile with the latest compiler. I found an issue with the version of dub this depends on, and it's ancient (1.7.2).

Can a release be done? I'll git-clone and run directly, but seems like there should be a release I would think at least whenever the server is updated.

**Comment by Geod24** [comment]
I could do it (there's 134 commits, I'll just go over it and sum up the changes), but I'd rather have a v0.9.0 release of Vibe.d available.
Currently this repo depends on `v0.9.0-beta.1` and we have `v0.9.0-rc.1` available. But even it already have some fixes in master (see https://github.com/vibe-d/vibe.d/compare/v0.9.0-rc.1...master ).
CC @s-ludwig .

**Comment by schveiguy** [comment]
I guess a release happened from @wilzbach but didn't close this issue.

**Comment by wilzbach** [comment]
> @wilzbach but didn't close this issue.

Well, he didn't know that this issue existed and he thought the $400 for tagging a release could be spent on a different feature of dub or its infrastructure.

Anyhow, Vibe.d 0.9.0 beta is still used here, so I guess this issue could be kept open as a reminder to fully upgrade to 0.9.0.

**Comment by Imperatorn** [comment]
https://github.com/Imperatorn/dub-registry
