### ISSUE TITLE
Import from Gitlab doesn't work

### ISSUE THREAD

**Issue by VindexTech** [dlang/dub-registry#477]
If try to add new package from Gitlab, we can see such message:

Failed to find a branch containing a valid package description file: 
master: Unexpected reply for 'https://gitlab.com/api/v4/projects/.../repository/files/%2Fdub.json/raw?ref=df99bf770be3fb573f2ccf6b49bcabc24ad160ea&private_token=***': Bad Request

If the same project exists on both Gitlab and GitHub, then import from GitHub works, but from Gitlab does not.

**Comment by sarneaud** [comment]
Looks like a dupe of this: https://github.com/dlang/dub-registry/issues/471
