### ISSUE TITLE
localhost link on publish page

### ISSUE THREAD

**Issue by adamdruppe** [dlang/dub-registry#480]
https://dub.pm/publish.html

" You can then register an account"

the link there points to localhost

**Comment by PetarKirov** [comment]
Strange, it works for me and also the source looks correct as well: https://github.com/dlang/dub-docs/blob/1244b915c9ede41e600cc4a3cb839fd08de58af5/views/publish.dt#L17

**Comment by WebFreak001** [comment]
this issue was made to the wrong repository, it has been fixed with https://github.com/dlang/dub-docs/pull/32
