### ISSUE TITLE
github API is broken, can't update packages anymore

### ISSUE THREAD

**Issue by 9il** [dlang/dub-registry#483]

**Comment by Geod24** [comment]
Error message ? Repro steps ?

**Comment by 9il** [comment]
![image](https://user-images.githubusercontent.com/845083/99142510-18e4fd00-2688-11eb-8e54-d94dd5ea294d.png)
![image](https://user-images.githubusercontent.com/845083/99142522-3e720680-2688-11eb-84fe-ec5bf2c4c90f.png)

**Comment by s-ludwig** [comment]
We need to switch to using an access token as it seems:

https://developer.github.com/changes/2020-02-14-deprecating-password-auth/

**Comment by s-ludwig** [comment]
Opened a PR: https://github.com/dlang/dub-registry/pull/484
