### ISSUE TITLE
Package registry seems to not updating packages automatically

### ISSUE THREAD

**Issue by tchaloupka** [dlang/dub-registry#492]
For example [vibe-core](https://code.dlang.org/packages/vibe-core), still `1.13.0` while `1.14.0` was released 3 days ago.
Or [dub](https://code.dlang.org/packages/dub) - still on `1.24.0` while `1.25.0` was released 8 days ago (and 2 more version between too aren't listed)

**Comment by SingingBush** [comment]
this seems to have been a problem for some time. I raised https://github.com/dlang/dub/issues/2128 the other day as ddbc v0.5.2 (tagged in feb) is still not available from the dub registry.

**Comment by s-ludwig** [comment]
Resolved now: https://github.com/dlang/dub/issues/2128#issuecomment-832699138

**Comment by SingingBush** [comment]
Seems that this may be an issue again. I'm currently waiting for the latest ddbc release (0.5.4) to be visible on the registry.
https://github.com/buggins/ddbc/releases/tag/v0.5.4

**Comment by WebFreak001** [comment]
seems to be updated now, so either someone did a manual update, or the automatic update that is run across all packages (which is getting slower and slower with more packages) came across it.

I think the issue here is actually fixed, but to improve the experience see #10
