### ISSUE TITLE
Login seems broken

### ISSUE THREAD

**Issue by p0nce** [dlang/dub-registry#499]
Using https://code.dlang.org/ since yesterday, and the bizarre issue that happens is:

Sometimes it show me that I'm logged, sometimes not after just a refresh. When managing packages, it will ask for login information again. 

No login attempt seems sucessful, but refresh may make me display that I'm logged. I can see my package and try to modify them.

If I add a category to a package, I will end up on login page, unable to login, and database is unmodified.

**Comment by p0nce** [comment]
Bug disappeared

**Comment by Geod24** [comment]
Sounds like jumping between servers to me ? I had that bug too recently, but it went away the day after.
