### ISSUE TITLE
Can't add a repository from a private Gitlab instance.

### ISSUE THREAD

**Issue by Gagege** [dlang/dub-registry#500]
Hello, I am trying to host a private dub registry and include packages from my company's privately hosted GitLab instance. I've set up a settings.json with my company's GitLab repo and access token, then successfully started a dub-registry via docker. I created a user and then attempted to add a new package. When I paste the URL (ex. `https://gitlab.{our domain}.com/foo/bar`) of one of our repos in the text box I get this message.

`Please enter a valid project URL or tuple to a GitHub, GitLab or BitBucket project, such as https://gitlab.com/dlang/dub or bitbucket/dlang/dub.`

Just to make sure, I was able to add the official vibe-d repo from gitlab.com. Am I doing something wrong, or is this a real issue? Thanks in advance.

**Comment by WebFreak001** [comment]
the gitlab provider in dub is hardcoded to a single gitlab instance - when you host your private dub registry you need to adjust the gitlab URL to your private one.

The error message is a problem with the frontend/validation (see https://github.com/dlang/dub-registry/blob/b85a6948fad80a2dfe57b985cba701b91aa735b4/views/my_packages.register.dt#L24)

I think you should be able to uncomment or adjust the pattern, then you should no longer get issues there as well.

**Comment by Gagege** [comment]
I already tried that :) and dub-registry couldn't parse the json out GitLab returned. I thought there might be an _official_ way to do this. If that's how you'd recommend doing it, then what's the purpose of setting `gitlab-url` and `gitlab-auth` in settings.json?

**Comment by WebFreak001** [comment]
well that gitlab-url in settings.json was exactly the one I was talking about to change.

**Comment by Gagege** [comment]
That works for now, so I thank you for that. I'm closing this.
