### ISSUE TITLE
transfer ownership for ddbc and hibernated

### ISSUE THREAD

**Issue by SingingBush** [dlang/dub-registry#516]
Since 2019 I've been keeping [ddbc](https://github.com/buggins/ddbc) and [hibernated](https://github.com/buggins/hibernated) up to date as the original author (Vadim Lopatin) no longer works on them.

Would it be possible to maintain them both of them in code.dlang.org?

https://code.dlang.org/packages/ddbc
https://code.dlang.org/packages/hibernated

**Comment by WebFreak001** [comment]
Do you want to move the repository link on dub to your own one or do you want to be made the dub author of these packages so you can manage them?

**Comment by WebFreak001** [comment]
can you share your dub username? @s-ludwig is the only one who can change the ownership I think though

**Comment by SingingBush** [comment]
I use _singingbush_ on dub as well.

**Comment by s-ludwig** [comment]
Okay, I've updated the ownership for both of them now. (We really should tackle #90 at some point)
