### ISSUE TITLE
Transfer the ownership of package "dogapi"

### ISSUE THREAD

**Issue by thechampagne** [dlang/dub-registry#518]
Hey ,

I want to transfer the ownership of "dogapi" package because github banned my previous account.

I changed the github url to the new repo on the package site.

**Comment by WebFreak001** [comment]
not sure what do you want to change? The dub login should be separate from github and as you were able to change the URL on dub I don't see what else should be changed.

**Comment by thechampagne** [comment]
I looked at the site now, Yeah it got updated.
