### ISSUE TITLE
Transfer ownership of dlangui

### ISSUE THREAD

**Issue by GrimMaple** [dlang/dub-registry#535]
Can I get ownership of [dlangui](https://github.com/buggins/dlangui)? Original author abandoned the project and I'm the only one maintaining it at the moment. My handle on dub is `grimmaple`

**Comment by s-ludwig** [comment]
I don't see an issue in general. But I would suggest to move the repository on github, if @buggins is okay with that. Possibly to a new "dlangui" organization, or to @dlang-community. That would ensure that whatever ownership changes occur in the future can be handled more easily.

**Comment by GrimMaple** [comment]
> I don't see an issue in general. But I would suggest to move the repository on github, if @buggins is okay with that. Possibly to a new "dlangui" organization, or to @dlang-community. That would ensure that whatever ownership changes occur in the future can be handled more easily.

I see an issue in that dlangui's version updated literally weeks ago, and dub hasn't picked on that yet. Actually, it's two releases back as of now (on dub). Usually I could force an update by hand, but I can't do that because of no ownership.

**Comment by WebFreak001** [comment]
yes we don't have organization accounts or shared ownership of packages on dub, but I think that's something we should definitely add in the future.

@s-ludwig there is also another issues that request a dub transfer (not just a transfer of github repo): https://github.com/dlang/dub-registry/issues/459

I haven't seen any issue about ownership management, so maybe we should open one to track what to do?

**Comment by s-ludwig** [comment]
Changed ownership.

@WebFreak001: Makes sense to track this in an issue. I think the minimum would be an invitation based system similar to what GitHub does. Groups/Organizations should also be simple to implement, as the user management code already supports that in principle.

**Comment by GrimMaple** [comment]
Thank you! To he honest, I didn't expect this to get resolved. But I sure am glad to be proven wrong :)
