### ISSUE TITLE
Multiple owners / admins for packages

### ISSUE THREAD

**Issue by WebFreak001** [dlang/dub-registry#536]
The DUB registry should support adding multiple DUB user accounts as owners to packages, to avoid issues such as #535 and #459

Also interesting would be having group / organization accounts (could even be linked to github organizations or teams)

There should probably also be the possibility to transfer package ownership by users themself (with recipient needing to accept, to not be able to spam users with foreign garbage packages)

**Comment by Geod24** [comment]
See https://github.com/dlang/dub-registry/issues/475
