### ISSUE TITLE
Password Resets Seem to be Broken for gmail Accounts

### ISSUE THREAD

**Issue by RubyTheRoobster** [dlang/dub-registry#538]
A while ago I tried to reset my password for my dub account, handle: rubytheroobster.  This account is tied to a gmail address, but no password reset email has been sent.  Trying to reset the password of a burner account I created when the password reset system was broken last time worked, making me believe that for some reason, password resets don't go through to gmail.

**Comment by RubyTheRoobster** [comment]
Apparently this is just me having this issue, and noone else.  Strange.

**Comment by s-ludwig** [comment]
Okay, we have now set up a Google backed noreply@dlang.org address, which should, in contrast to the previous one, be reliable when it comes to sending to the big e-mail providers (Gmail included, obviously). Can you retry?

**Comment by RubyTheRoobster** [comment]
It works now.  Thank you!
