### ISSUE TITLE
Taking over ownership of `openmethods` package

### ISSUE THREAD

**Issue by ahmetsait** [dlang/dub-registry#547]
I've been using openmethods and made a PR to fix an issue (jll63/openmethods.d#20) but the author hasn't responded to the PR (opened Jul 6) or my email (sent Jul 16) yet.

Would be nice if I could have access to the Dub package to maintain it rather than having to create another one.

CC @WebFreak001

**Comment by WebFreak001** [comment]
which repo should we transfer the package to and which DUB account?

**Comment by ahmetsait** [comment]
My dub registry username is `ahmetsait`, pointing the repo url to https://github.com/ahmetsait/openmethods.d should suffice.

**Comment by WebFreak001** [comment]
your fork is missing tags, you need to make sure you have at least all the version tags as the original repo

**Comment by ahmetsait** [comment]
Alright let me figure out how to sync tags in git.

**Comment by ahmetsait** [comment]
Done. https://github.com/ahmetsait/openmethods.d/tags

Anything else?

**Comment by jll63** [comment]
Hi,

@ahmetsait Sorry I missed the notifications for your PR.

I am happy to see that at least one person uses `openmethods`. I have not had the time to maintain my knowledge of D, nor to keep up with the evolution of the language. I am fine with transferring ownership. I will be happy to assist if, in the future, someone wants to make more complex improvements.

**Comment by ahmetsait** [comment]
@WebFreak001 I think we can continue with the transfer, and since @jll63 gave me write access to jll63/openmethods.d the package repo URL does not need updating.

**Comment by WebFreak001** [comment]
neat, @s-ludwig we only need a dub user transfer of `openmethods` to `ahmetsait` now

**Comment by PetarKirov** [comment]
Perhaps it's better to transfer openmethods to [dlang-community](https://github.com/dlang-community/)?

**Comment by ahmetsait** [comment]
@jll63 #550 is deployed now so would you like to give me access to dub package yourself?

**Comment by WebFreak001** [comment]
I gave you admin permissions for the package, ownership stays the same right now until that feature is added to the registry. If you need ownership earlier, feel free to reopen.
