### ISSUE TITLE
Transfer ownership of dackson

### ISSUE THREAD

**Issue by leeavital** [dlang/dub-registry#552]
Hello,

I'd like to transfer ownership of [dackson](https://code.dlang.org/packages/dackson)  to  @zkxjzmswkwl (username on code.dlang.org: zkxj) 

Thank you!

**Comment by s-ludwig** [comment]
Done!

**Comment by WebFreak001** [comment]
@s-ludwig btw check out #550 to let users at least share packages themselves (full ownership transfer still manual though)

**Comment by s-ludwig** [comment]
Missed that. I'll have a look.
