### ISSUE TITLE
IPv6 support (with a AAAA record)

### ISSUE THREAD

**Issue by deavmi** [dlang/dub-registry#555]
Originally [posted here](https://forum.dlang.org/post/mggcmsvmlcufcywrotei@forum.dlang.org):

Hey guys (and gals),

Not sure if this is the correct place to post this as I couldn't find a specific topic for it that would fit.

My question is regarding the infrastructure (and whoever maintains it) that runs code.dlang.org and what I presume to be the service which Dub connects to in order to pull package lists from.

I live in a town with an ISP that solely provides an IPv6 connection, this isn't a problem, DNS64 gets around most problems and in any case the sites I care about I can reach. However, I cannot reach code.dlang.org and was wondering if there was any plans to get it IPv6 compliant. Complete with an AAAA record and V6 address to go along with it.

My current work around is... kinda expensive. I have to use my mobile data for pulling packages and pushing to Dub.

Thanks!
Keep it 100.

**Comment by PetarKirov** [comment]
Hi @deavmi, thanks for reaching out! I've contacted with the server admin and we've enabled IPv6. On both the server and DNS level. Take a look:

```
curl --ipv6 -v 'https://code.dlang.org'
*   Trying [2606:4700:3033::ac43:d6ac]:443...
* Connected to code.dlang.org (2606:4700:3033::ac43:d6ac) port 443 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=dlang.org
*  start date: Oct  6 04:55:25 2023 GMT
*  expire date: Jan  4 04:55:24 2024 GMT
*  subjectAltName: host "code.dlang.org" matched cert's "*.dlang.org"
*  issuer: C=US; O=Google Trust Services LLC; CN=GTS CA 1P5
*  SSL certificate verify ok.
* using HTTP/2
* h2 [:method: GET]
* h2 [:scheme: https]
* h2 [:authority: code.dlang.org]
* h2 [:path: /]
* h2 [user-agent: curl/8.1.1]
* h2 [accept: */*]
* Using Stream ID: 1 (easy handle 0xff0aa0)
> GET / HTTP/2
> Host: code.dlang.org
> User-Agent: curl/8.1.1
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 200 
< date: Tue, 31 Oct 2023 13:21:45 GMT
< content-type: text/html; charset=UTF-8
< cf-cache-status: DYNAMIC
< report-to: ...
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< server: cloudflare
< cf-ray: ...
< alt-svc: h3=":443"; ma=86400
< 
<!DOCTYPE html>
...

Enjoy!

**Comment by deavmi** [comment]
> Hi @deavmi, thanks for reaching out! I've contacted with the server admin and we've enabled IPv6 on both the server and DNS level. Take a look:
> 
> `curl --ipv6 -v 'https://code.dlang.org'`
> Enjoy!

Works perfectly! Dankie!

**Comment by PetarKirov** [comment]
You're welcome!
