### ISSUE TITLE
Attempt to register a package fails because it is "already registered"

### ISSUE THREAD

**Issue by ArthaTi** [dlang/dub-registry#561]
!["A package with the same name is already registered" error when registering a package](https://github.com/dlang/dub-registry/assets/28842854/5f73e1d6-94c1-4b8b-b2bd-26088c75cf79)

While registering https://github.com/Samerion/Fluid, package name "fluid" in dub, I get the error above. There is no such package registered however.

![DUB search results for fluid: 0 packages](https://github.com/dlang/dub-registry/assets/28842854/8358e0dc-5897-48b5-927d-f64bbf29d08d)

![DUB command line failing to find a package with the name](https://github.com/dlang/dub-registry/assets/28842854/b00f6d37-f66b-444c-b4c8-300cf17c4e08)

Fluid has recently been renamed from Glui. The package Glui is registered, however under the name "glui", pointing at an archived repository: https://github.com/Samerion/Glui; That means Glui and Fluid are now two separate repositories, as suggested by the website:

> If you want to rename the project, create a new repository and keep the old one. 

However I created a new repository for Glui, while reusing the old repository for Fluid. It appears the error has been caused because DUB happened to crawl through the `glui` package while I was in the process of renaming the repository, with the dub.json already updated to reflect the change.

As a result, `fluid` appears to now be a dead package name, unable to be claimed. Looking through the code of the repository I thought it should be automatically released after a new search update cycle starts, so I waited the night, but that doesn't appear to have worked. I would be glad if the name was deleted from the database so I could claim it now.

**Comment by s-ludwig** [comment]
I just tried to add "https://github.com/Samerion/Fluid" as one of my packages and it worked without issues. There was also no trace of an empty "fluid" entry in the database. I'm not sure what exactly, but maybe this was just a temporary issue with the two packages interfering? I'll at least add the conflicting package name to that error message - maybe it was actually still picking up "glui" instead of "fluid".

**Comment by s-ludwig** [comment]
Package is registered now and improved error message has been merged.
