### ISSUE TITLE
Transfer package `dfl` to DUB user `rayerd`

### ISSUE THREAD

**Issue by WebFreak001** [dlang/dub-registry#564]
Currently an outdated fork is registered, the original author now wants to publish the package and on Discord imperatorn confirmed that they want to migrate it to the actual author.

New dub username: `rayerd`

**Comment by s-ludwig** [comment]
Can't we use the new permission system do to that on the user side now? I've never actually tried it out since it has been implemented.

**Comment by Rayerd** [comment]
He deleted the registry.
I have just registered.

**Comment by s-ludwig** [comment]
Okay, that works, too! Otherwise, there is the "permissions" tab under `My Packages` -> `dfl`, where it should be possible to add someone else with administrator privileges, which just has the advantage of not requiring to re-configure the categories and logo graphics.

**Comment by s-ludwig** [comment]
Oh, and download statistics get reset, too, when deleting a package from the registry, so it needs some time until its "score" has fully recovered.

**Comment by Rayerd** [comment]
I don't think it matters since the old registry was abandoned.
