### ISSUE TITLE
Second level indent is not working in README.md

### ISSUE THREAD

**Issue by Rayerd** [dlang/dub-registry#565]
How can I write it so that it will appear the same?

- DUB
![image](https://github.com/dlang/dub-registry/assets/586833/c151e037-0b68-4ea2-b833-af217239f0ca)

- GitHub
![image](https://github.com/dlang/dub-registry/assets/586833/932bf744-7d22-48b3-b077-68dab823f06b)

**Comment by s-ludwig** [comment]
There appears to be a discrepancy between the CommonMark spec and the Markdown parser here, as our parser currently requires four spaces of indentation in order to count items as part of the parent list item, while it should already work with two spaces.

**Comment by Rayerd** [comment]
Should I use two or four spaces before the sublist?

**Comment by s-ludwig** [comment]
Yeah, that should make it work. I'll open a ticket against the parser, too.

**Comment by Rayerd** [comment]
It seems to have been fixed.

- DUB
![image](https://github.com/dlang/dub-registry/assets/586833/479b4627-c073-49b5-b56e-7d0614cad2a6)
