### ISSUE TITLE
The display differs between GitHub and the DUB website.

### ISSUE THREAD

**Issue by Rayerd** [dlang/dub-registry#572]
![image](https://github.com/dlang/dub-registry/assets/586833/d548954c-97f3-4fe7-b0a7-c6ee4e794e7a)

GitHub
![image](https://github.com/dlang/dub-registry/assets/586833/9d46303b-d72d-4550-83af-d35d242eb3a9)

DUB
![image](https://github.com/dlang/dub-registry/assets/586833/44190edb-6b89-42ea-8dea-4cf570799eb7)

DUB does not interpret underscores.

**Comment by Rayerd** [comment]
In the case of embedded type, it seems to display the same.

**Comment by s-ludwig** [comment]
The version displayed by code.dlang.org, belonging to the newest version tag, is from this older commit: https://github.com/Rayerd/dfl/blob/ddffe731398767b0cda19f1e5b4898091f4b52f5/README.md?plain=1#L79

Looking at the page for the `~master` version, it displays the options correctly: https://code.dlang.org/packages/dfl/~master

![grafik](https://github.com/dlang/dub-registry/assets/1645969/3fbf5019-6ef9-4cfa-8642-a43f865e17d4)

**Comment by Rayerd** [comment]
You're right.
The underscore will be misinterpreted if it's not embedded.
