### ISSUE TITLE
dub registration is impossible

### ISSUE THREAD

**Issue by gitgit3** [dlang/dub-registry#574]
I've been 30 minutes now trying to create an account so that I can upload my project. Here:
https://code.dlang.org/register

The registration form simply comes up with error after error. Usually the password is not acceptable. I have used a password at least 8 chars, containing at least one number and one letter and one of the (-_) as indicated. Still it refuses.

Then after refreshing the form, it now tells me that 'one of' my username or email or password is not acceptable.

You need to do two things here.
1. Make the error message VERY specific. "You've done something wrong" is NOT helpful.
2. Remove your password restrictions. They do not help anyone. In fact you are removing the ability for me to use a highly random as secure machine generated password. And personally I never use a password where I must push the shift key.

**Comment by s-ludwig** [comment]
Can you please post the concrete error that you received, possibly even a screenshot? I can neither reproduce the mentioned issues, nor can I see anything matching the description in the source code. There is only a length requirement and no character set requirements. I can't see any indication for that in the UI either. There is also no error message combining username and password for the registration form. Finally, all error messages regarding the password that I found in the code are specific, such as "The password must be at least 8 characters long." or "The password and the confirmation differ.".

**Comment by gitgit3** [comment]
The password entered here was zaqwsxcde321 and you can see that the error message is not specific at all. "Invalid user/email or password", that's 3 fields

![login-failure-1](https://github.com/user-attachments/assets/402bdd66-df4c-4951-9ec3-7ca00532de32)

**Comment by gitgit3** [comment]
Additionally to the previous post, I tried a second time with a different email address and it tld me that the username was taken. So I tried a 3rd time changing only the username and using the same password consistently. This 3rd message was the same as the first "Invalid user/email or password". And we are back to square one. Round and round we go....

**Comment by s-ludwig** [comment]
Okay, after fiddling around with this for a while, I've found out what causes the issue - using uppercase letters in the "user name" field. The error message is actually from the log in process, which gets triggered internally after a successful registration. For some reason that consequently fails, which is never supposed to happen. I'll look into a fix later, but for now you should be able to register using your original e-mail address and a lower case user name.

**Comment by gitgit3** [comment]
Perfect. Thank you for the super-quick response!
