### ISSUE TITLE
Cannot sign up.

### ISSUE THREAD

**Issue by AmarokIce** [dlang/dub-registry#576]
when i try to register, i got the error message ` Invalid user/email or password. `, it looks like the error message for sign in not sign up. im pretty sure there was no problem with the message I filled in.

i think it akin with #199?

**Comment by aleferri** [comment]
I can't also register i tried all my emails and changed repeatedly the user, but to no avail: "Invalid user/email or password" is it. Please fix i need to register a package.

**Comment by tvandera** [comment]
Same here

**Comment by tvandera** [comment]
Any news on this?

**Comment by s-ludwig** [comment]
I recently made a fix for https://github.com/dlang/dub-registry/issues/574 - does this apply here, too (mixed case user name)?

**Comment by AmarokIce** [comment]
> I recently made a fix for #574 - does this apply here, too (mixed case user name)?

it still happend, I tried lower case but didn't work

**Comment by tvandera** [comment]
Screenshot:

![Screenshot](https://github.com/user-attachments/assets/e4a29abc-4dc7-4ca2-ba50-c72637f2067e)

**Comment by s-ludwig** [comment]
I've deployed a new build with manually upgraded dependencies (still waiting for a new dub version to be tagged) and that appears to have fixed it from a quick test.

**Comment by AmarokIce** [comment]
mach thanks! now it work
