### ISSUE TITLE
Trigger Manual Update should be Sync Now.

### ISSUE THREAD

**Issue by MartinNowak** [dlang/dub-registry#92]
Instead of scheduling an update that happens at an unknown moment we should simply offer an update now button. If we hit any rate limit, then we can report that to the user and tell him that the package will eventually be updated automatically.
This provides a much better user experience.

I'd still like to add an optional github oauth permission so that we can use hooks instead of polling.

**Comment by s-ludwig** [comment]
With the just deployed changes, this may have become a non-issue for the next time to come. Due to cache use improvements and avoiding superfluous disconnects to the GitHub API server, updates are now a *lot* faster. Adding an index to the URL cache MongoDB collection also improved things a little.

**Comment by s-ludwig** [comment]
BTW, the cache will possibly need to warm up over the course of maybe a few hours.

**Comment by s-ludwig** [comment]
A full update now takes a bit over 3 minutes.

**Comment by MartinNowak** [comment]
3 minutes sounds really good. So we don't need a hook based solution now, but it will still be needed in the long-term.

**Comment by s-ludwig** [comment]
Definitely!

**Comment by MartinNowak** [comment]
See #291
